apiVersion: apps/v1   
kind: Deployment
metadata:
  name: deployment
  labels:
    type: backend
spec:
  selector:
    matchLabels:
      type: backend
  replicas: 3
  template:
    metadata:
      labels: 
        type: backend
    spec:
      containers:
      - name: nginx
        image: nginx 
      
