apiVersion: v1
kind: ReplicationController
metadata: 
  name: rc
  labels:
    type: backend
spec:
  template:
    metadata:
      name: demo
      labels: 
        type: backend 
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3      
    
    
 